/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/responses": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.responses.id"];
          timestamp?: parameters["rowFilter.responses.timestamp"];
          year?: parameters["rowFilter.responses.year"];
          year_match?: parameters["rowFilter.responses.year_match"];
          pronouns?: parameters["rowFilter.responses.pronouns"];
          pronouns_match?: parameters["rowFilter.responses.pronouns_match"];
          phone?: parameters["rowFilter.responses.phone"];
          nickname?: parameters["rowFilter.responses.nickname"];
          bio?: parameters["rowFilter.responses.bio"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["responses"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** responses */
          responses?: definitions["responses"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.responses.id"];
          timestamp?: parameters["rowFilter.responses.timestamp"];
          year?: parameters["rowFilter.responses.year"];
          year_match?: parameters["rowFilter.responses.year_match"];
          pronouns?: parameters["rowFilter.responses.pronouns"];
          pronouns_match?: parameters["rowFilter.responses.pronouns_match"];
          phone?: parameters["rowFilter.responses.phone"];
          nickname?: parameters["rowFilter.responses.nickname"];
          bio?: parameters["rowFilter.responses.bio"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.responses.id"];
          timestamp?: parameters["rowFilter.responses.timestamp"];
          year?: parameters["rowFilter.responses.year"];
          year_match?: parameters["rowFilter.responses.year_match"];
          pronouns?: parameters["rowFilter.responses.pronouns"];
          pronouns_match?: parameters["rowFilter.responses.pronouns_match"];
          phone?: parameters["rowFilter.responses.phone"];
          nickname?: parameters["rowFilter.responses.nickname"];
          bio?: parameters["rowFilter.responses.bio"];
        };
        body: {
          /** responses */
          responses?: definitions["responses"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
}

export interface definitions {
  responses: {
    /**
     * Format: uuid
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: string;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    timestamp?: string;
    /** Format: integer */
    year?: number;
    /** Format: ARRAY */
    year_match?: number[];
    /** Format: text */
    pronouns?: string;
    /** Format: ARRAY */
    pronouns_match?: string[];
    /** Format: character varying */
    phone?: string;
    /** Format: text */
    nickname?: string;
    /** Format: text */
    bio?: string;
  };
}

export interface parameters {
  /**
   * @description Preference
   * @enum {string}
   */
  preferParams: "params=single-object";
  /**
   * @description Preference
   * @enum {string}
   */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /**
   * @description Preference
   * @enum {string}
   */
  preferCount: "count=none";
  /** @description Filtering Columns */
  select: string;
  /** @description On Conflict */
  on_conflict: string;
  /** @description Ordering */
  order: string;
  /** @description Limiting and Pagination */
  range: string;
  /**
   * @description Limiting and Pagination
   * @default items
   */
  rangeUnit: string;
  /** @description Limiting and Pagination */
  offset: string;
  /** @description Limiting and Pagination */
  limit: string;
  /** @description responses */
  "body.responses": definitions["responses"];
  /** Format: uuid */
  "rowFilter.responses.id": string;
  /** Format: timestamp with time zone */
  "rowFilter.responses.timestamp": string;
  /** Format: integer */
  "rowFilter.responses.year": string;
  /** Format: ARRAY */
  "rowFilter.responses.year_match": string;
  /** Format: text */
  "rowFilter.responses.pronouns": string;
  /** Format: ARRAY */
  "rowFilter.responses.pronouns_match": string;
  /** Format: character varying */
  "rowFilter.responses.phone": string;
  /** Format: text */
  "rowFilter.responses.nickname": string;
  /** Format: text */
  "rowFilter.responses.bio": string;
}

export interface operations {}

export interface external {}
